# Generated by Django 3.1.5 on 2021-05-02 11:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customer_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='account_no',
            field=models.CharField(default=1, max_length=13, validators=[django.core.validators.MinLengthValidator(13)], verbose_name='Volume Number'),
            preserve_default=False,
        ),
    ]
